### PR TITLE
replace prismjs with highlightjs

### PR DESCRIPTION
**Pull request by mackenza**
seems faster... and supports Lua.

### CODE REVIEW

**Comment by vlucas** [comment]
Thanks! :+1:

**Comment by mackenza** [comment]
does it seem faster to you?

**Comment by vlucas** [comment]
Yes - WAY faster. Just pulled it down and tried it locally.

**Comment by vlucas** [comment]
It's live and deployed: http://devdata.io/

**Comment by mackenza** [comment]
there are many more themes. I chose that one because it looked most like the old one you had. If you want, feel free to browse the highlightjs site for other themes.

**Pull request merged**
